package com.campus.common;

public enum NotificationType {
    WELCOME,
    COMMUNITY_COMMENT_RECEIVED,
    COMMUNITY_REPLY_RECEIVED,
    COMMUNITY_POST_LIKED,
    RESOURCE_APPROVED,
    RESOURCE_REJECTED,
    RESOURCE_OFFLINED,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED
}
