package com.campus.common;

public enum NotificationType {
    WELCOME,
    COMMUNITY_REPLY_RECEIVED,
    COMMUNITY_POST_LIKED,
    COMMUNITY_POST_COMMENTED,
    RESOURCE_APPROVED,
    RESOURCE_REJECTED,
    RESOURCE_OFFLINED,
    RESOURCE_UPLOADED,
    VERIFICATION_APPROVED,
    VERIFICATION_REJECTED,
    JOB_APPLICATION_SUBMITTED,
    RESUME_UPLOADED
}
