spring:
  datasource:
    url: jdbc:h2:mem:campus-local;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

app:
  resource-storage:
    type: local
    local-root: .local-storage/resources
  resource-preview:
    local-root: .local-storage/previews

platform:
  integrations:
    redis:
      enabled: false
    elasticsearch:
      enabled: false
    minio:
      enabled: false
